CFLAGS = -Wall -g -fno-PIC -m32 -mpreferred-stack-boundary=2 -Wno-unused-variable -Wno-unused-const-variable -Wno-unused-function
LDFLAGS = -m32 -no-pie

.PHONY: all clean

all: sppb

clean:
	-rm -f sppb sppb.o
	-rm -f *~
